import { ComputeEngine, AIModel, UserSettings } from '@/types';

export const DEFAULT_SETTINGS: UserSettings = {
  computeEngine: 'cloudflare-ai',
  defaultModel: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
  defaultSampler: 'Euler a',
  defaultAspectRatio: '1:1',
  defaultBatchCount: 1,
  defaultSteps: 25,
  defaultGuidance: 7.0,
  defaultStyleStrength: 0.65,
  defaultLoraWeight: 0.5,
  defaultNegativePrompt: 'low resolution, blurry, distorted, bad hands, bad face, deformed, extra fingers, watermark, text',
  darkMode: false,
  historyLimit: 50,
  enableD1Sync: false,
  enableNsfw: true,
  autoEnhancePrompt: true,
};

export const SAMPLING_METHODS = [
  'Euler a',
  'DPM++ 2M Karras',
  'DPM++ SDE Karras',
  'DDIM',
  'LCM',
  'UniPC',
];

export const SCHEDULER_TYPES = [
  'Karras',
  'Exponential',
  'Normal',
  'SGM Uniform',
  'Simple',
];

export const ASPECT_RATIOS = [
  { label: '1:1 1024×1024 正方形', value: '1:1', icon: '⏹️', w: 1024, h: 1024 },
  { label: '16:9 1280×720 横屏', value: '16:9', icon: '🖥️', w: 1280, h: 720 },
  { label: '9:16 720×1280 手机屏', value: '9:16', icon: '📱', w: 720, h: 1280 },
  { label: '4:3 1024×768 经典屏', value: '4:3', icon: '🖼️', w: 1024, h: 768 },
  { label: '3:4 768×1024 竖屏', value: '3:4', icon: '📄', w: 768, h: 1024 },
];

export const COMPUTE_ENGINES: ComputeEngine[] = [
  {
    id: 'cloudflare-ai',
    name: 'Cloudflare Workers AI (服务端受控)',
    type: 'cloudflare-ai',
    description: '通过服务端环境变量 CLOUDFLARE_ACCOUNT_ID/AI_TOKEN 安全调优，出图极稳',
    isDefault: true,
  },
  {
    id: 'pollinations',
    name: 'Pollinations 开放算力池',
    type: 'pollinations',
    description: '免 API Key，支持 FLUX, SDXL，秒级无缝生成',
    isDefault: false,
  },
  {
    id: 'siliconflow',
    name: 'SiliconFlow 硅基流动云算力',
    type: 'custom-api',
    endpoint: 'https://api.siliconflow.cn/v1/image/generations',
    description: '国内极速 FLUX.1 / SDXL 高清生成',
    isDefault: false,
  },
  {
    id: 'openai',
    name: 'OpenAI DALL-E 3 官方引擎',
    type: 'dall-e',
    description: '顶级语言理解能力，画质高逼真',
    isDefault: false,
  },
];

export const AI_MODELS: AIModel[] = [
  {
    id: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
    name: 'SDXL Base 1.0 (出厂默认旗舰画质)',
    translatedName: 'SDXL Base 1.0 旗舰大模型',
    description: 'Cloudflare 官方画质原汁原味旗舰大模型，光影通透细腻，默认开启 1536/2048 超分放大',
    provider: 'cloudflare',
    category: 'sdxl',
    cfModelPath: '@cf/stabilityai/stable-diffusion-xl-base-1.0',
    isPopular: true,
    isFavorite: true,
    isFree: true,
    recommendedReason: '出厂默认首选：25 步，CFG 7.0，高精质感呈现',
  },
  {
    id: '@cf/bytedance/stable-diffusion-xl-lightning',
    name: 'ByteDance SDXL Lightning (极速预览模式)',
    translatedName: 'SDXL Lightning 极速预览版',
    description: '字节跳动 4-步闪电推理模型，专为快速试构图与草稿验证设计',
    provider: 'cloudflare',
    category: 'sdxl',
    cfModelPath: '@cf/bytedance/stable-diffusion-xl-lightning',
    isPopular: true,
    isFree: true,
  },
  {
    id: 'flux',
    name: 'FLUX.1 极速旗舰版 (免费算力)',
    translatedName: 'FLUX.1 极速画质王者',
    description: 'Black Forest Labs 顶级画质大模型，出图逼真、细节震撼',
    provider: 'pollinations',
    category: 'flux',
    isPopular: true,
    isFree: true,
  },
  {
    id: 'flux-realism',
    name: 'FLUX Realism 写实摄影版',
    translatedName: 'FLUX 写实摄影大模型',
    description: '专注于摄影级肖像、自然光影与超清晰肌理细节',
    provider: 'pollinations',
    category: 'realistic',
    isPopular: true,
    isFree: true,
  },
  {
    id: 'flux-anime',
    name: 'FLUX Anime 二次元大师版',
    translatedName: 'FLUX 动漫美学大模型',
    description: '极致细腻的二次元画风与水彩插画',
    provider: 'pollinations',
    category: 'anime',
    isPopular: true,
    isFree: true,
  },
  {
    id: 'flux-3d',
    name: 'FLUX 3D CG 电影渲染版',
    translatedName: 'FLUX 3D CG 画质大模型',
    description: '媲美皮克斯与虚幻引擎 3D 渲染质感',
    provider: 'pollinations',
    category: '3d',
    isFree: true,
  },
  {
    id: 'turbo',
    name: 'SDXL Turbo 闪电极速版',
    translatedName: 'SDXL Turbo 极速大模型',
    description: '秒级极速生成，适合快速创意探索',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:animagine-xl-3.1',
    name: 'Animagine XL 3.1 动漫大师版',
    translatedName: 'Animagine 二次元大师 3.1',
    description: '专业日系动漫插画模型，线条极佳',
    provider: 'pollinations',
    category: 'anime',
    isFree: true,
  },
  {
    id: 'civitai:cyberrealistic-v4.1',
    name: 'CyberRealistic V4.1 赛博写实',
    translatedName: 'CyberRealistic 赛博现实主义',
    description: '真实肖像、光彩肌理与摄影级质感',
    provider: 'pollinations',
    category: 'realistic',
    isFree: true,
  },
  {
    id: 'civitai:dreamshaper-xl-v2',
    name: 'DreamShaper XL V2 梦幻塑造者',
    translatedName: 'DreamShaper 梦幻大模型 V2',
    description: '兼顾写实与奇幻艺术创作',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:ink-wash-painting-xl',
    name: 'Ink Wash Painting 水墨国风',
    translatedName: '水墨写意传统国风大模型',
    description: '诗情画意的水墨宣纸质感',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:ghibli-style-xl',
    name: 'Ghibli Style 吉卜力治愈风',
    translatedName: '吉卜力吉风治愈系大模型',
    description: '宫崎骏动画般阳光清新色彩',
    provider: 'pollinations',
    category: 'anime',
    isFree: true,
  },
  {
    id: 'civitai:midjourney-v6-style',
    name: 'Midjourney V6 艺术美学预设',
    translatedName: 'MJ V6 艺术美学构图版',
    description: '震撼光影与艺术构图质感',
    provider: 'pollinations',
    category: 'sdxl',
    isFree: true,
  },
  {
    id: 'civitai:anything-v5',
    name: 'Anything V5 经典二次元',
    translatedName: 'Anything V5 通用动漫版',
    description: '经典通用型动漫绘图大模型',
    provider: 'pollinations',
    category: 'anime',
    isFree: true,
  },
  {
    id: 'black-forest-labs/FLUX.1-schnell',
    name: 'SiliconFlow FLUX.1 Schnell',
    translatedName: '硅基流动 FLUX 极速版',
    description: 'SiliconFlow 托管高效率模型',
    provider: 'custom',
    category: 'flux',
    needsApiKey: true,
  },
  {
    id: 'dall-e-3',
    name: 'OpenAI DALL·E 3 官方引擎',
    translatedName: 'DALL·E 3 官方画质模型',
    description: 'OpenAI 官方旗舰图像引擎',
    provider: 'openai',
    category: 'realistic',
    needsApiKey: true,
  },
];

export const PRESET_MODELS = AI_MODELS;
